import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { Bookmark, ChevronLeft, Clock, Heart, MapPin, Search, Send, SlidersHorizontal, Users, Wallet, X, CloudRain, Footprints, Sparkles } from 'lucide-react';
import { emitExperience } from '../../experience';
import { commitRitualState, loadRitualState } from '../../ritualState';
import { loadPersisted } from '../../persistence';
import { scoreTingo } from '../../domain/tingo';

type FeedMode = 'all' | 'places' | 'trips';
type Place = {
  id:number; name:string; area:string; type:string; cost:string; duration:string; match:number;
  image:string; saved:boolean; suggested:boolean; tags:string[]; summary:string; coco:string;
  evidence:{ icon:'heart'|'clock'|'wallet'|'route'|'rain'|'group'; text:string }[];
};
type Trip = {
  id:number; title:string; author:string; match:number; days:number; places:number; image:string;
  description:string; saved:boolean; tags:string[]; route:string[]; budget:string; pace:string;
};
type Detail = {kind:'place';item:Place}|{kind:'trip';item:Trip}|null;

const img = (id:string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=84`;

const placeSeed:Place[] = [
  {id:1,name:'Kissa You',area:'Ginza',type:'Quiet café · Retro',cost:'RM32 est.',duration:'1.5h',match:97,image:img('photo-1495474472287-4d71bcdd2085'),saved:false,suggested:false,tags:['quiet cafe near shibuya','cafe with good matcha','cafe','low energy afternoon','retro'],summary:'A calm retro kissaten with a compact stop length and low walking load.',coco:'Best when the group wants somewhere memorable without turning the afternoon into another mission.',evidence:[{icon:'heart',text:'Strong café fit for Mei’s preference profile'},{icon:'clock',text:'Fits a 90-minute floating block'},{icon:'wallet',text:'Low spend relative to today’s food budget'},{icon:'group',text:'Easy group stop with flexible dwell time'}]},
  {id:2,name:'Streamer Coffee Shibuya',area:'Shibuya',type:'Café · Minimal',cost:'RM28 est.',duration:'1h',match:96,image:img('photo-1445116572660-236099ec97a0'),saved:false,suggested:false,tags:['quiet cafe near shibuya','cafe with good matcha','cafe','shibuya','low energy afternoon'],summary:'A short coffee stop close to the Shibuya route, useful when energy is dipping.',coco:'A practical reset before a busier evening block.',evidence:[{icon:'route',text:'Near the active Shibuya route'},{icon:'clock',text:'Only needs about 60 minutes'},{icon:'heart',text:'Matches café-hopping preference'},{icon:'group',text:'Low-commitment stop for mixed group energy'}]},
  {id:3,name:'Sakurai Japanese Tea Experience',area:'Omotesando',type:'Tea · Matcha',cost:'RM45 est.',duration:'1.5h',match:94,image:img('photo-1515823662972-da6a2e4d3002'),saved:false,suggested:false,tags:['cafe with good matcha','matcha','quiet cafe near shibuya','tea','low energy afternoon'],summary:'Tea-focused stop with a quieter atmosphere than a standard café crawl.',coco:'Pick this when “matcha” matters more than squeezing in another attraction.',evidence:[{icon:'heart',text:'Direct match for the matcha search intent'},{icon:'clock',text:'Comfortable 90-minute stop'},{icon:'wallet',text:'Still inside the afternoon discretionary budget'},{icon:'route',text:'Reasonable detour from central Tokyo route'}]},
  {id:4,name:'Yanaka Ginza',area:'Yanaka',type:'Local streets · Food',cost:'RM35 est.',duration:'2h',match:93,image:img('photo-1528360983277-13d401cdc186'),saved:false,suggested:false,tags:['hidden gems in tokyo','local','budget-safe food','street food','hidden gem'],summary:'Small shops and local snacks in a neighbourhood that feels less checklist-heavy.',coco:'Good when you want “Tokyo” without another giant landmark.',evidence:[{icon:'heart',text:'Strong hidden-gem and food preference fit'},{icon:'wallet',text:'Easy to control spend by choosing snacks individually'},{icon:'route',text:'Walkable cluster instead of scattered stops'},{icon:'group',text:'Members can browse at different speeds'}]},
  {id:5,name:'Jimbocho Book Town',area:'Jimbocho',type:'Books · Hidden gem',cost:'Free–RM40',duration:'2h',match:91,image:img('photo-1521587760476-6c12a4b040da'),saved:false,suggested:false,tags:['hidden gems in tokyo','hidden gem','shopping','low energy afternoon','rainy day indoor activities'],summary:'Used-book streets, tiny shops and indoor browsing with almost no schedule pressure.',coco:'A good “wander until something catches you” block.',evidence:[{icon:'rain',text:'Mostly indoor / covered browsing works in light rain'},{icon:'wallet',text:'Free unless you choose to buy something'},{icon:'clock',text:'Can shrink from 2 hours to 45 minutes easily'},{icon:'heart',text:'Fits slow discovery rather than attraction-chasing'}]},
  {id:6,name:'Tokyo Photographic Art Museum',area:'Ebisu',type:'Museum · Indoor',cost:'RM38 est.',duration:'2h',match:92,image:img('photo-1564399579883-451a5d44ec08'),saved:false,suggested:false,tags:['rainy day indoor activities','museum','indoor','low energy afternoon','culture'],summary:'A weather-safe indoor stop with seating, predictable timing and nearby cafés.',coco:'One of the safest swaps when rain kills an outdoor floating block.',evidence:[{icon:'rain',text:'Fully indoor rainy-day option'},{icon:'clock',text:'Predictable 2-hour visit window'},{icon:'route',text:'Easy to pair with Ebisu / Meguro'},{icon:'group',text:'Works even if group energy is uneven'}]},
  {id:7,name:'Toyosu Senkyaku Banrai',area:'Toyosu',type:'Indoor market · Food',cost:'RM50 est.',duration:'2h',match:95,image:img('photo-1515003197210-e0cd71810b5f'),saved:false,suggested:false,tags:['rainy day indoor activities','budget-safe food','food','market','group-friendly'],summary:'Covered food browsing with many price points and easy group splitting.',coco:'Useful when everyone wants something different but nobody wants a formal Court debate over lunch.',evidence:[{icon:'rain',text:'Covered / indoor-friendly choice'},{icon:'group',text:'Multiple food options reduce preference conflict'},{icon:'wallet',text:'Easy to keep each person near their own budget'},{icon:'clock',text:'Flexible 90–120 minute stop'}]},
  {id:8,name:'Onigiri Asakusa Yadoroku',area:'Asakusa',type:'Food · Budget',cost:'RM18 est.',duration:'45m',match:94,image:img('photo-1601050690597-df0568f70950'),saved:false,suggested:false,tags:['budget-safe food','food','cheap eats','low energy afternoon','asakusa'],summary:'Fast, affordable food stop that leaves budget and time for later.',coco:'This is the “feed everyone without spending the afternoon budget” choice.',evidence:[{icon:'wallet',text:'One of the lowest-cost food options in the feed'},{icon:'clock',text:'Only about 45 minutes'},{icon:'route',text:'Easy add-on around Asakusa'},{icon:'group',text:'Low commitment if the group wants different dinner plans'}]},
  {id:9,name:'Ueno Park Bench Loop',area:'Ueno',type:'Nature · Low energy',cost:'Free',duration:'1h',match:90,image:img('photo-1526481280695-3c687fd643ed'),saved:false,suggested:false,tags:['low energy afternoon','nature','budget-safe','slow','park'],summary:'A deliberately easy park loop with plenty of places to stop and sit.',coco:'Choose this when the plan needs breathing room more than another “must-see”.',evidence:[{icon:'wallet',text:'Free activity'},{icon:'clock',text:'Easy to shorten at any point'},{icon:'heart',text:'Supports a slower afternoon pace'},{icon:'group',text:'Good recovery block for tired members'}]},
  {id:10,name:'Meguro Riverside',area:'Meguro',type:'Scenic walk · Calm',cost:'Free',duration:'1h',match:89,image:img('photo-1524413840807-0c3cb6fa808d'),saved:false,suggested:false,tags:['low energy afternoon','nature','hidden gems in tokyo','scenic','budget-safe'],summary:'Flat riverside wandering with cafés nearby if the group wants to stop early.',coco:'A low-risk filler block that still feels like travelling.',evidence:[{icon:'wallet',text:'Free unless you stop for food'},{icon:'route',text:'Simple linear route with easy exits'},{icon:'clock',text:'Fits a one-hour floating block'},{icon:'heart',text:'Good scenic reset without heavy walking'}]},
  {id:11,name:'Koenji Vintage Walk',area:'Koenji',type:'Vintage · Shopping',cost:'RM40 est.',duration:'2h',match:90,image:img('photo-1519501025264-65ba15a82390'),saved:false,suggested:false,tags:['hidden gems in tokyo','shopping','vintage','local','budget-safe'],summary:'A flexible neighbourhood browse with vintage stores, record shops and cafés.',coco:'Good for splitting attention without actually splitting the group.',evidence:[{icon:'heart',text:'Strong vintage / local discovery fit'},{icon:'wallet',text:'Browsing is free; spend stays optional'},{icon:'group',text:'Different members can browse different shops nearby'},{icon:'clock',text:'Can expand or contract with the day'}]},
  {id:12,name:'Shinjuku Gyoen Greenhouse',area:'Shinjuku',type:'Nature · Indoor',cost:'RM15 est.',duration:'1.5h',match:88,image:img('photo-1500530855697-b586d89ba3ee'),saved:false,suggested:false,tags:['rainy day indoor activities','nature','low energy afternoon','shinjuku','budget-safe'],summary:'Green space with an indoor greenhouse option when weather turns.',coco:'A softer alternative when the group still wants greenery but not rain.',evidence:[{icon:'rain',text:'Greenhouse keeps part of the visit weather-safe'},{icon:'wallet',text:'Low ticket cost'},{icon:'heart',text:'Nature fit without long transit'},{icon:'clock',text:'Works as a 60–90 minute reset'}]},
  {id:13,name:'Ameya-Yokocho Snack Crawl',area:'Ueno',type:'Food · Market',cost:'RM30 est.',duration:'1.5h',match:93,image:img('photo-1554797589-7241bb691973'),saved:false,suggested:false,tags:['budget-safe food','food','market','group-friendly','hidden gems in tokyo'],summary:'Affordable snack-by-snack browsing where everyone can choose independently.',coco:'Better than one expensive restaurant when the group wants variety.',evidence:[{icon:'wallet',text:'Easy to cap spend item-by-item'},{icon:'group',text:'Different food preferences can coexist'},{icon:'route',text:'Compact market street'},{icon:'clock',text:'No reservation pressure'}]},
  {id:14,name:'Mori Art Museum',area:'Roppongi',type:'Art · Indoor',cost:'RM58 est.',duration:'2.5h',match:86,image:img('photo-1561214115-f2f134cc4912'),saved:false,suggested:false,tags:['rainy day indoor activities','museum','indoor','art','culture'],summary:'Longer indoor art stop for a rain-heavy day when the group wants something substantial.',coco:'Use this when “indoor backup” needs to feel like a real destination, not just killing time.',evidence:[{icon:'rain',text:'Fully indoor weather-safe activity'},{icon:'clock',text:'Can replace a larger outdoor block'},{icon:'group',text:'Works well as a shared anchor'},{icon:'wallet',text:'Higher cost, but still within activities allowance'}]},
  {id:15,name:'Daikanyama T-Site',area:'Daikanyama',type:'Books · Café · Design',cost:'RM25 est.',duration:'2h',match:92,image:img('photo-1495446815901-a7297e633e8d'),saved:false,suggested:false,tags:['quiet cafe near shibuya','hidden gems in tokyo','cafe','low energy afternoon','design'],summary:'Books, design and coffee in a slower neighbourhood near Shibuya.',coco:'The “still near Shibuya but please less Shibuya” option.',evidence:[{icon:'route',text:'Close enough to pair with Shibuya'},{icon:'heart',text:'Café + browsing matches slow discovery'},{icon:'clock',text:'Flexible 1–2 hour dwell time'},{icon:'group',text:'Easy for members to browse independently nearby'}]},
];

const tripSeed:Trip[] = [
 {id:1,title:'Tokyo slow food + vintage streets',author:'Aki',match:94,days:5,places:12,image:img('photo-1540959733332-eab4deabeeaf'),description:'Five days of neighbourhood food, vintage stores, cafés and intentionally loose afternoons.',saved:false,tags:['food','vintage','hidden gems in tokyo'],route:['Yanaka Ginza','Koenji Vintage Walk','Tsukiji side streets'],budget:'Student-friendly with one splurge dinner',pace:'2 anchors + 1 floating block per day'},
 {id:2,title:'Rain-proof Tokyo weekend',author:'Mina',match:93,days:3,places:8,image:img('photo-1493976040374-85c8e12f0c0e'),description:'Museums, covered markets and cafés arranged so bad weather does not wreck the day.',saved:false,tags:['rainy day indoor activities','rainy-day','indoor','cafe'],route:['Tokyo Photographic Art Museum','Toyosu Senkyaku Banrai','Mori Art Museum'],budget:'Mid-range indoor weekend',pace:'Low walking · reliable indoor anchors'},
 {id:3,title:'Quiet cafés around Shibuya',author:'Rin',match:96,days:2,places:7,image:img('photo-1501339847302-ac426a4a7cbb'),description:'A deliberately gentle café route around Shibuya, Omotesando and Daikanyama.',saved:false,tags:['quiet cafe near shibuya','cafe with good matcha','cafe','low energy afternoon'],route:['Streamer Coffee Shibuya','Sakurai Tea','Daikanyama T-Site'],budget:'RM120/day food + cafés',pace:'Slow mornings · one optional evening'},
 {id:4,title:'Tokyo on a student food budget',author:'Suki',match:95,days:4,places:13,image:img('photo-1504674900247-0877df9cc836'),description:'Cheap eats, markets, neighbourhood snacks and free walks with room for one special meal.',saved:false,tags:['budget-safe food','food','student budget','market'],route:['Yadoroku Onigiri','Ameya-Yokocho','Yanaka Ginza'],budget:'RM90/day excluding stay',pace:'Food-led · short transit hops'},
 {id:5,title:'Low-energy Tokyo reset',author:'Tom',match:91,days:3,places:8,image:img('photo-1500534314209-a25ddb2bd429'),description:'Parks, riverside stops, bookshops and cafés for days when the group is running out of battery.',saved:false,tags:['low energy afternoon','slow','nature','cafe'],route:['Ueno Park','Meguro Riverside','Jimbocho Book Town'],budget:'Mostly free / low-cost',pace:'Long buffers · sitting breaks built in'},
 {id:6,title:'Hidden Tokyo without the checklist',author:'Noa',match:92,days:4,places:10,image:img('photo-1480796927426-f609979314bd'),description:'Small neighbourhoods, book streets, markets and local browsing instead of landmark collecting.',saved:false,tags:['hidden gems in tokyo','hidden gem','local','shopping'],route:['Jimbocho','Koenji','Yanaka'],budget:'Flexible; shopping optional',pace:'Neighbourhood clusters · low transit'},
 {id:7,title:'Matcha + quiet mornings',author:'Yui',match:90,days:2,places:6,image:img('photo-1515823662972-da6a2e4d3002'),description:'Tea, breakfast, gardens and soft mornings with almost no nightlife pressure.',saved:false,tags:['cafe with good matcha','matcha','quiet cafe near shibuya','slow'],route:['Sakurai Tea','Kissa You','Shinjuku Gyoen'],budget:'RM100/day food + tea',pace:'Morning-focused · free afternoons'},
 {id:8,title:'Indoor culture day for heavy rain',author:'Kai',match:89,days:1,places:4,image:img('photo-1561214115-f2f134cc4912'),description:'A one-day indoor backup route that still feels intentional, not like emergency filler.',saved:false,tags:['rainy day indoor activities','museum','indoor','culture'],route:['Mori Art Museum','Tokyo Photographic Art Museum','Daikanyama T-Site'],budget:'RM140 activities + food',pace:'Two major indoor anchors'},
];

const searchSuggestions=['quiet cafe near shibuya','cafe with good matcha','hidden gems in tokyo','rainy day indoor activities','budget-safe food','low energy afternoon'];

function patchPersisted(name:string,patch:{saved?:boolean;added?:boolean}){try{const key='cococrunch:v1';const raw=localStorage.getItem(key);const parsed=raw?JSON.parse(raw):{};const current=Array.isArray(parsed.recommendations)?parsed.recommendations:[];const exists=current.some((r:{name?:string})=>r.name===name);parsed.recommendations=exists?current.map((r:{name?:string})=>r.name===name?{...r,...patch}:r):[...current,{name,saved:Boolean(patch.saved),added:Boolean(patch.added)}];localStorage.setItem(key,JSON.stringify(parsed));}catch{/* progressive enhancement */}}

function matchesQuery(text:string,q:string){
  if(!q)return true;
  const normalized=q.toLowerCase();
  const words=normalized.split(/\s+/).filter(Boolean);
  const hay=text.toLowerCase();
  return hay.includes(normalized)||words.filter(w=>w.length>2).every(w=>hay.includes(w))||words.filter(w=>w.length>3).some(w=>hay.includes(w));
}

export default function ExploreReplicaV3(){
 const [host,setHost]=useState<HTMLElement|null>(null);const [query,setQuery]=useState('');const [searchOpen,setSearchOpen]=useState(false);const [filtersOpen,setFiltersOpen]=useState(false);const [mode,setMode]=useState<FeedMode>('all');const [category,setCategory]=useState('For you');const [detail,setDetail]=useState<Detail>(null);const [toast,setToast]=useState<string|null>(null);
 const persisted=useMemo(()=>loadPersisted(),[]);const destination=persisted.destination||persisted.tripIntent?.destination||'Tokyo';useMemo(()=>scoreTingo(persisted.tingoAnswers??[]),[persisted.tingoAnswers]);
 const savedMap=useMemo(()=>new Map((persisted.recommendations??[]).map(r=>[r.name,r])),[persisted.recommendations]);
 const [places,setPlaces]=useState(()=>placeSeed.map(p=>({...p,saved:Boolean(savedMap.get(p.name)?.saved),suggested:Boolean(savedMap.get(p.name)?.added)})));
 const [trips,setTrips]=useState(tripSeed);
 useEffect(()=>{const find=()=>setHost(document.querySelector('.explore-screen'));find();const o=new MutationObserver(find);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect();},[]);
 useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),1600);return()=>window.clearTimeout(t);},[toast]);
 const q=query.trim().toLowerCase();
 const filteredPlaces=places.filter(p=>matchesQuery(`${p.name} ${p.area} ${p.type} ${p.tags.join(' ')} ${p.summary}`,q));
 const filteredTrips=trips.filter(t=>matchesQuery(`${t.title} ${t.author} ${t.tags.join(' ')} ${t.description} ${t.route.join(' ')}`,q));
 const categoryPlaces=category==='Cafés'?places.filter(p=>/café|tea/i.test(p.type)):category==='Food'?places.filter(p=>/food|market/i.test(p.type)):category==='Nature'?places.filter(p=>/nature|scenic|park|garden/i.test(p.type)):places;
 function savePlace(place:Place){if(place.saved){setPlaces(xs=>xs.map(x=>x.id===place.id?{...x,saved:false}:x));patchPersisted(place.name,{saved:false});setToast('Removed from saved');return;}emitExperience({type:'capture-place',place:place.name,save:()=>{const current=loadRitualState();const savedIdeas=[...(current.savedIdeas??[]).filter(x=>x.name!==place.name),{name:place.name,source:'prototype-catalog'}];if(!commitRitualState({savedIdeas}))return false;setPlaces(xs=>xs.map(x=>x.id===place.id?{...x,saved:true}:x));patchPersisted(place.name,{saved:true});setToast('Saved!');return true;}})}
 function suggestPlace(place:Place){const next=!place.suggested;setPlaces(xs=>xs.map(x=>x.id===place.id?{...x,suggested:next}:x));patchPersisted(place.name,{added:next});setToast(next?'Suggested to group':'Suggestion removed')}
 function saveTrip(trip:Trip){setTrips(xs=>xs.map(x=>x.id===trip.id?{...x,saved:!x.saved}:x));setToast(trip.saved?'Removed from saved':'Trip inspiration saved')}
 if(!host)return null;
 const iconFor=(kind:Place['evidence'][number]['icon'])=>kind==='heart'?<Heart size={16}/>:kind==='clock'?<Clock size={16}/>:kind==='wallet'?<Wallet size={16}/>:kind==='route'?<MapPin size={16}/>:kind==='rain'?<CloudRain size={16}/>:<Users size={16}/>;
 const PlaceCard=({place}:{place:Place})=><article className="x3-card" onClick={()=>setDetail({kind:'place',item:place})}><div className="x3-photo"><img src={place.image} alt=""/><span>PLACE</span><button className={place.saved?'saved':''} onClick={e=>{e.stopPropagation();savePlace(place)}}><Heart size={17} fill={place.saved?'currentColor':'none'}/></button>{place.suggested&&<em>Suggested</em>}</div><div className="x3-cardbody"><b>{place.name}</b><small>{place.area} · {place.type}</small><strong>♥ {place.match}% match</strong><small><Clock size={12}/> {place.duration}</small></div></article>;
 const TripCard=({trip}:{trip:Trip})=><article className="x3-card" onClick={()=>setDetail({kind:'trip',item:trip})}><div className="x3-photo"><img src={trip.image} alt=""/><span>TRIP</span><button className={trip.saved?'saved':''} onClick={e=>{e.stopPropagation();saveTrip(trip)}}><Heart size={17} fill={trip.saved?'currentColor':'none'}/></button></div><div className="x3-cardbody"><b>{trip.title}</b><small>◉ {trip.author}</small><small>{trip.days} days · {trip.places} places</small><strong>♥ {trip.match}% match</strong></div></article>;
 const ui=<div className="x3-root">
  <header className="x3-head"><div><span>EXPLORE · COCO PICKS</span><h1>Explore</h1></div><small>Places + trips that fit your people, pace and budget.</small></header>
  <button className="x3-search" onClick={()=>setSearchOpen(true)}><Search size={18}/><span>{query||'Search cafés, places, trips...'}</span><SlidersHorizontal size={18}/></button>
  <div className="x3-chips">{['For you','Places','Trips','Cafés','Food','Nature'].map(c=><button key={c} className={category===c?'active':''} onClick={()=>{setCategory(c);setMode(c==='Places'?'places':c==='Trips'?'trips':'all')}}>{c}</button>)}</div>
  <section className="x3-feature" onClick={()=>setSearchOpen(true)}><img src={img('photo-1540959733332-eab4deabeeaf')} alt="Tokyo street"/><div><small>COCO FOUND A DETOUR</small><b>Find your next<br/>favourite place.</b></div><i>→</i></section>
  {(mode==='all'||mode==='places')&&<section className="x3-section"><div className="x3-title"><h2>{category==='For you'?'Recommended for you':category==='Places'?'Places for your trip':category}</h2><button onClick={()=>{setMode('places');setCategory('Places')}}>See all</button></div><div className="x3-grid">{categoryPlaces.slice(0,mode==='places'?15:8).map(p=><PlaceCard key={p.id} place={p}/>)}</div></section>}
  {(mode==='all'||mode==='trips')&&<section className="x3-section"><div className="x3-title"><h2>Trips from the community</h2><button onClick={()=>{setMode('trips');setCategory('Trips')}}>See all</button></div><div className="x3-grid">{trips.slice(0,mode==='trips'?8:6).map(t=><TripCard key={t.id} trip={t}/>)}</div></section>}
  {searchOpen&&<div className="x3-full"><div className="x3-searchtop"><button onClick={()=>setSearchOpen(false)}><ChevronLeft/></button><label><Search size={17}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="quiet cafe near shibuya"/>{query&&<button onClick={()=>setQuery('')}><X size={15}/></button>}</label><button onClick={()=>setFiltersOpen(true)}><SlidersHorizontal/></button></div>{!q?<div className="x3-suggestions"><h3>Try searching</h3>{searchSuggestions.map(s=><button key={s} onClick={()=>setQuery(s)}><Search size={15}/>{s}</button>)}<div>🔭<b>Coco is looking...</b><small>Places and trips that fit this trip.</small></div></div>:<div className="x3-results"><div className="x3-tabs"><button className={mode==='all'?'active':''} onClick={()=>setMode('all')}>All ({filteredPlaces.length+filteredTrips.length})</button><button className={mode==='places'?'active':''} onClick={()=>setMode('places')}>Places ({filteredPlaces.length})</button><button className={mode==='trips'?'active':''} onClick={()=>setMode('trips')}>Trips ({filteredTrips.length})</button></div><div className="x3-note">🔭 <span><b>Here are some places and trips for you!</b><small>Matched against the words you searched, plus trip fit.</small></span></div><div className="x3-grid">{mode!=='trips'&&filteredPlaces.map(p=><PlaceCard key={`sp${p.id}`} place={p}/>)}{mode!=='places'&&filteredTrips.map(t=><TripCard key={`st${t.id}`} trip={t}/>)}</div>{filteredPlaces.length+filteredTrips.length===0&&<div className="x3-empty"><Sparkles/><b>No exact match yet.</b><small>Try one of Coco’s suggested phrases.</small></div>}</div>}</div>}
  {filtersOpen&&<div className="x3-shade" onClick={()=>setFiltersOpen(false)}><section className="x3-filter" onClick={e=>e.stopPropagation()}><i/><div><h2>Filters</h2><button onClick={()=>setFiltersOpen(false)}><X/></button></div><h3>Content type</h3><nav><button className={mode==='all'?'active':''} onClick={()=>setMode('all')}>All</button><button className={mode==='places'?'active':''} onClick={()=>setMode('places')}>Places</button><button className={mode==='trips'?'active':''} onClick={()=>setMode('trips')}>Trips</button></nav><h3>Trip fit</h3><nav><button className="active">Near our route</button><button>Budget-safe</button><button>Low energy</button><button>Rainy-day</button><button>Group-friendly</button></nav><h3>Vibe</h3><nav><button>☕ Café</button><button>🍴 Food</button><button>🌿 Nature</button><button>🏛 Culture</button><button>🛍 Shopping</button><button>◇ Hidden gem</button></nav><footer><button onClick={()=>setMode('all')}>Reset</button><button onClick={()=>setFiltersOpen(false)}>Show results</button></footer></section></div>}
  {detail?.kind==='place'&&(()=>{const place=places.find(p=>p.id===detail.item.id)??detail.item;return <div className="x3-full x3-detail"><div className="x3-detailhero"><img src={place.image} alt=""/><button onClick={()=>setDetail(null)}><ChevronLeft/></button><button className={place.saved?'saved':''} onClick={()=>savePlace(place)}><Heart fill={place.saved?'currentColor':'none'}/></button></div><div className="x3-detailbody"><div className="x3-detailkicker">PLACE · {place.area.toUpperCase()}</div><h2>{place.name}</h2><p>{place.type} · {destination}</p><div className="x3-match">♥ {place.match}% match for your group</div><p className="x3-summary">{place.summary}</p><h3>Why this fits your trip</h3><div className="x3-evidence">{place.evidence.map((e,i)=><div key={i}>{iconFor(e.icon)}<span>{e.text}</span></div>)}</div><div className="x3-coco"><b>Coco’s take</b><p>“{place.coco}”</p></div><div className="x3-detailactions"><button onClick={()=>savePlace(place)}><Bookmark/>{place.saved?'Saved':'Save'}</button><button className={place.suggested?'suggested':''} onClick={()=>suggestPlace(place)}><Send/>{place.suggested?'Suggested to group':'Suggest to group'}</button></div>{place.suggested&&<small className="x3-governance">Proposal only · official itinerary still needs group confirmation.</small>}</div></div>})()}
  {detail?.kind==='trip'&&(()=>{const trip=trips.find(t=>t.id===detail.item.id)??detail.item;return <div className="x3-full x3-detail"><div className="x3-detailhero"><img src={trip.image} alt=""/><button onClick={()=>setDetail(null)}><ChevronLeft/></button><button className={trip.saved?'saved':''} onClick={()=>saveTrip(trip)}><Heart fill={trip.saved?'currentColor':'none'}/></button></div><div className="x3-detailbody"><div className="x3-detailkicker">COMMUNITY TRIP · PUBLIC</div><h2>{trip.title}</h2><p>by {trip.author}</p><div className="x3-match">♥ {trip.match}% match · {trip.days} days · {trip.places} places</div><p className="x3-summary">{trip.description}</p><div className="x3-tripmeta"><span><Wallet/> {trip.budget}</span><span><Footprints/> {trip.pace}</span></div><h3>Places in this trip</h3><div className="x3-route">{trip.route.map((name,i)=>{const p=places.find(x=>x.name.includes(name)||name.includes(x.name.split(' ')[0]));return <button key={name} onClick={()=>p&&setDetail({kind:'place',item:p})}><span>{i+1}</span><b>{name}</b><small>{p?'Open place details':'Community route stop'}</small></button>})}</div><div className="x3-tags">{trip.tags.map(t=><span key={t}>{t}</span>)}</div><button className="x3-save-trip" onClick={()=>saveTrip(trip)}><Bookmark/>{trip.saved?'Trip inspiration saved':'Save trip inspiration'}</button></div></div>})()}
  {toast&&<div className="x3-toast">{toast}</div>}
 </div>;
 return createPortal(ui,host);
}
