import React, { useMemo, useState } from 'react';
import { ArrowRight, Box, Check, CircleDollarSign, CloudRain, Gavel, Heart, Home, Map, PackageCheck, ReceiptText, Route, Send, Sparkles, Users } from 'lucide-react';
import { familyReport, savedPlace, splitBill } from './features';

const steps = [
  { id: 'me', label: 'Know me', icon: Heart },
  { id: 'us', label: 'Know us', icon: Users },
  { id: 'plan', label: 'Plan', icon: Map },
  { id: 'court', label: 'Court', icon: Gavel },
  { id: 'reality', label: 'Reality', icon: CloudRain },
  { id: 'family', label: 'Report', icon: Send },
  { id: 'budget', label: 'Budget', icon: ReceiptText },
  { id: 'memories', label: 'Memories', icon: Box },
] as const;

type StepId = typeof steps[number]['id'];

const palette = { cream: '#FFF8E7', sangria: '#930500', blue: '#95BBEA' };

function Coco({ mood = 'idle', compact = false }: { mood?: 'idle' | 'happy' | 'panic'; compact?: boolean }) {
  return <div className={`coco coco-${mood}${compact ? ' coco-compact' : ''}`} aria-label={`Coco mascot ${mood}`}><span className="antenna left"/><span className="antenna right"/><span className="coco-body"><span className="eye left"/><span className="eye right"/><span className="mouth"/></span><span className="leg l1"/><span className="leg l2"/><span className="leg r1"/><span className="leg r2"/></div>;
}

function CaptureCapsule({ active }: { active: boolean }) {
  return <div className={`capsule-stage${active ? ' is-captured' : ''}`} aria-hidden="true"><div className="capture-place">伏</div><div className="capture-orbit"/><div className="capture-capsule"><span/></div></div>;
}

function MapRide({ riding, onRide }: { riding: boolean; onRide: () => void }) {
  return <div className={`route-map${riding ? ' is-riding' : ''}`}><div className="map-label one">Tsukiji</div><div className="map-label two">Daikanyama</div><div className="map-label three">Shibuya</div><svg viewBox="0 0 320 130" role="img" aria-label="Schematic itinerary route"><path d="M30 95 C90 28, 155 115, 285 38"/><circle cx="30" cy="95" r="6"/><circle cx="160" cy="83" r="6"/><circle cx="285" cy="38" r="6"/></svg><div className="coco-rider"><Coco compact mood="happy"/><span className="tiny-rider">•</span></div><button className="map-action" onClick={onRide}><Route size={17}/>{riding ? 'Coco is on the move' : 'Ride with Coco'}</button></div>;
}

export default function App() {
  const [active, setActive] = useState<StepId>('me');
  const [courtChoice, setCourtChoice] = useState<'ramen' | 'sushi' | null>(null);
  const [gacha, setGacha] = useState<string | null>(null);
  const [replanned, setReplanned] = useState(false);
  const [replanConfirmed, setReplanConfirmed] = useState(false);
  const [reported, setReported] = useState(false);
  const [printed, setPrinted] = useState(false);
  const [captured, setCaptured] = useState(false);
  const [riding, setRiding] = useState(false);
  const [privacy, setPrivacy] = useState<'status' | 'area' | 'exact'>('area');

  const index = steps.findIndex((step) => step.id === active);
  const next = steps[Math.min(index + 1, steps.length - 1)]?.id ?? 'memories';
  const mood = active === 'reality' && !replanConfirmed ? 'panic' : courtChoice || replanConfirmed || reported || printed || captured || riding ? 'happy' : 'idle';
  const activeStep = steps[index];

  const content = useMemo(() => {
    if (active === 'me') return <section className="content-block"><p className="eyebrow">01 · Coco Profile</p><h2>Coco learns how you travel.</h2><div className="trait-grid">{['Slow mornings','Food-first','Budget-aware','Flexible plans'].map((trait, i) => <button key={trait} className={i < 3 ? 'chip selected' : 'chip'}>{trait}</button>)}</div><div className="soft-note"><Sparkles size={18}/><span>These preferences influence pacing, recommendations, budget trade-offs and conflict detection.</span></div></section>;
    if (active === 'us') return <section className="content-block"><p className="eyebrow">02 · Group Travel DNA</p><h2>Your group mostly agrees… except here.</h2><div className="metric-list"><div><span>Food</span><strong>High priority</strong></div><div><span>Pace</span><strong>Relaxed</strong></div></div><div className="accent-card"><span>⚠ Preference conflict</span><b>Mei: Must-Go sushi · JH: Strongly avoid raw food</b><small>Coco won’t average this away. Send it to Court.</small></div></section>;
    if (active === 'plan') return <section className="content-block"><p className="eyebrow">03 · Executable plan</p><div className="title-row"><div><h2>Tokyo · 5 days</h2><p className="muted">Slow, food-first, leave room to wander.</p></div><div className="health-pill" aria-label="Plan Health 86 out of 100">86</div></div><div className="budget-snapshot"><div><span>Trip budget</span><strong>RM 2,400</strong></div><div><span>Planned</span><strong>RM 1,760</strong></div><div><span>Buffer</span><strong>RM 640</strong></div></div><div className="timeline"><div className="timeline-item"><span>10:00</span><div><b>Tsukiji food walk</b><small>Must-Go · protected</small></div><strong>⚓ Anchor</strong></div><div className="timeline-item"><span>14:30</span><div><b>Daikanyama cafés</b><small>Fits group pace · RM38 est.</small></div><strong>🫧 Floating</strong></div><div className="timeline-item mystery"><span>17:00</span><div><b>Mystery Window</b><small>Reserved for a viable surprise</small></div><strong>🎰 Open</strong></div></div><div className="why-card"><span>WHY THIS?</span><b>Food-first without rushing the group.</b><small>Tsukiji satisfies Mei’s Must-Go, cafés preserve the relaxed pace, and the open block protects spontaneity without exceeding the buffer.</small></div><MapRide riding={riding} onRide={() => { setRiding(false); requestAnimationFrame(() => setRiding(true)); }}/><div className="plan-health"><span>Plan Health</span><small>Budget ✓ · Walking moderate · 1 weather-sensitive block</small></div></section>;
    if (active === 'court') return <section className="content-block"><p className="eyebrow">04 · Group Court</p><h2>We disagree. Decide transparently.</h2><div className="court-score"><span>Current vote</span><b>2 · 2 tie</b><small>Gacha unlocks only because the vote is tied.</small></div><div className="court-stack"><button className={courtChoice === 'ramen' ? 'court-choice selected' : 'court-choice'} onClick={() => setCourtChoice('ramen')}><span>🍜</span><b>Ramen dinner</b><small>2 supporters · cheaper</small></button><button className={courtChoice === 'sushi' ? 'court-choice selected' : 'court-choice'} onClick={() => setCourtChoice('sushi')}><span>🍣</span><b>Sushi dinner</b><small>2 supporters · Must-Go conflict</small></button></div><button className="gacha" onClick={() => setGacha(Math.random() > 0.5 ? 'Ramen wins the tie.' : 'Sushi wins the tie.')}>🎰 Resolve this tie with Gacha</button>{gacha && <div className="result">{gacha}<span>Decision recorded. No other random tool is used.</span></div>}</section>;
    if (active === 'reality') return <section className="content-block"><p className="eyebrow">05 · Reality happens</p><h2>Heavy rain hits your outdoor block.</h2>{!replanned ? <><div className="weather-callout"><CloudRain size={24}/><div><b>17:00 outdoor market is no longer viable.</b><small>Anchor stays protected. Coco found a backup within the remaining budget.</small></div></div><div className="ghost-row"><span>👻 Ghost revival</span><b>Underground food hall</b><small>+12 min · +RM8 · indoors · Food priority match</small></div><button className="primary" onClick={() => setReplanned(true)}>Preview minimum-loss replan <ArrowRight size={18}/></button></> : !replanConfirmed ? <><div className="replan-preview"><span>CHANGE PREVIEW</span><div><b>Keep</b><small>Tsukiji Anchor</small></div><div><b>Replace</b><small>Outdoor market → Underground food hall</small></div><div><b>Move</b><small>Mystery Window → 19:00</small></div><div><b>Impact</b><small>+RM8 · +12 min · promise preserved</small></div></div><div className="confirm-row"><button className="secondary" onClick={() => setReplanned(false)}>Not now</button><button className="primary inline" onClick={() => setReplanConfirmed(true)}>Confirm change</button></div></> : <><div className="success"><Check size={22}/><div><b>Plan repaired.</b><small>Tsukiji Anchor preserved · Mystery Window moved · +RM8 · Trip Promise intact.</small></div></div><button className="undo-link" onClick={() => { setReplanConfirmed(false); setReplanned(true); }}>Undo this change</button><div className="prayer-ritual"><div className="incense">〰︎</div><b>Still worried? Coco recommends praying.</b><small>Entertainment only. Scientific backup plan stays active.</small></div></>}</section>;
    if (active === 'family') return <section className="content-block"><p className="eyebrow">06 · Family Window</p><h2>Reassurance, not surveillance.</h2><div className="privacy-row" role="group" aria-label="Report privacy level">{(['status','area','exact'] as const).map((level) => <button key={level} className={privacy === level ? 'privacy active' : 'privacy'} onClick={() => setPrivacy(level)}>{level === 'status' ? 'Status only' : level === 'area' ? 'Approx. area' : 'Exact'}</button>)}</div><div className="family-status"><span>🟡 Plan changed, but everything is okay.</span><b>{privacy === 'status' ? 'Kyoto trip · safe' : privacy === 'area' ? familyReport.area : `${familyReport.area} · exact location shared`}</b><small>{familyReport.note}</small><small>{familyReport.withGroup ? 'Still with the group' : 'Travelling solo'} · expected back {familyReport.returnTime}</small></div><div className="reassurance-contract"><span>Reassurance Contract</span><small>Notify only for: city arrival · &gt;2h delay · group split · return-time change</small></div><button className="primary" onClick={() => setReported(true)}><Send size={18}/>{reported ? 'Coco delivered it.' : 'Send one-tap report'}</button>{reported && <div className="delivery"><Coco mood="happy" compact/><span>🪳💨 Coco carried the note out of the screen.</span></div>}</section>;
    if (active === 'budget') return <section className="content-block"><p className="eyebrow">07 · Budget + Split Bill</p><h2>Know the trip cost before the receipt arrives.</h2><div className="budget-snapshot detailed"><div><span>Total budget</span><strong>RM 2,400</strong></div><div><span>Spent</span><strong>RM 1,288</strong></div><div><span>Reserved</span><strong>RM 472</strong></div><div><span>Free buffer</span><strong>RM 640</strong></div></div><div className={`printer${printed ? ' is-printing' : ''}`}><div className="printer-mouth"/><div className="receipt-card"><div className="receipt-head"><ReceiptText size={20}/><b>COCOCRUNCH TRAVEL OFFICE</b></div><div className="receipt-line"><span>Total</span><strong>{splitBill.currency} {splitBill.total.toLocaleString()}</strong></div>{splitBill.members.map((member) => <div className="receipt-line" key={member.name}><span>{member.name}</span><strong>{member.amount.toLocaleString()}</strong></div>)}</div></div><button className="primary" onClick={() => { setPrinted(false); requestAnimationFrame(() => setPrinted(true)); }}><ReceiptText size={18}/>{printed ? 'RRRIP— print again' : 'Print & tear receipt'}</button>{printed && <div className="printed">PAID · budget history updated</div>}</section>;
    return <section className="content-block"><p className="eyebrow">08 · Memories</p><h2>Your trip lives in a box, not a grid.</h2><div className="memory-box"><div className="trunk-lid">POSTCARDS · TICKETS · RECEIPTS</div><div className="trunk-body"><span className="postcard">KYOTO<br/>wish you were here</span><span className="ticket">TOKYO<br/>17:40</span><span className="stub">¥480</span></div></div><CaptureCapsule active={captured}/><div className="capture-card"><PackageCheck size={22}/><div><b>{savedPlace.name}</b><small>{savedPlace.reason}</small></div><button className={captured ? 'vote active' : 'vote'} onClick={() => { setCaptured(false); requestAnimationFrame(() => setCaptured(true)); }}>{captured ? 'Captured' : 'Capture'}</button></div>{captured && <div className="result">WHOOP— location absorbed into Coco Capsule.<span>Saved to Ghost Wish / Saved Places.</span></div>}</section>;
  }, [active, courtChoice, gacha, replanned, replanConfirmed, reported, printed, captured, riding, privacy]);

  return <main className="app-shell" style={{ '--cream': palette.cream, '--sangria': palette.sangria, '--blue': palette.blue } as React.CSSProperties}><header className="topbar"><div><p className="brand-kicker">COCOCRUNCH</p><h1>COCO IN YOUR AREA.</h1><p className="subtitle">Trips get messy. Coco rolls with it.</p></div><Coco mood={mood}/></header><section className="trip-summary"><div><span className="summary-label">CURRENT TRIP</span><strong>Tokyo · 5 days</strong></div><div className="summary-meta"><span><CircleDollarSign size={15}/> RM 2,400</span><span><Users size={15}/> 4 travellers</span></div></section><div className="section-context"><span>{String(index + 1).padStart(2, '0')}</span><div><small>{activeStep.label}</small><b>{active === 'reality' ? 'During the trip' : active === 'memories' ? 'After the trip' : 'Before the trip'}</b></div></div>{content}{active !== 'memories' && <button className="next" onClick={() => setActive(next)}>Continue <ArrowRight size={17}/></button>}<footer className="bottom-nav"><button onClick={() => setActive('me')} className={active === 'me' || active === 'us' ? 'active' : ''}><Home size={18}/><span>Home</span></button><button onClick={() => setActive('plan')} className={active === 'plan' || active === 'court' ? 'active' : ''}><Map size={18}/><span>Plan</span></button><button onClick={() => setActive('reality')} className={active === 'reality' ? 'active' : ''}><Route size={18}/><span>During</span></button><button onClick={() => setActive('family')} className={active === 'family' ? 'active' : ''}><Send size={18}/><span>Report</span></button><button onClick={() => setActive('memories')} className={active === 'budget' || active === 'memories' ? 'active' : ''}><Box size={18}/><span>Memory</span></button></footer></main>;
}
